<a href="https://colab.research.google.com/github/Aryan-986/Machine-learning-and-DA-with-py/blob/main/8.%20Feature%20Extraction%20of%20Text%20data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

About the dataset

1. id: Unique id for a new article

2. title: the title of a news article

3. author: author of the newa article

4. label: a label that marks whether the news article is real or fake



*   Fake news
*   real news



Importing the Dependencies

In [3]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer


In [5]:
# Install if needed:
# pip install scikit-learn nltk

import nltk
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Example text snippets (replace with your transcript)
documents = [
    "Machine learning is fascinating.",
    "Text feature extraction converts text to vectors.",
    "TF-IDF weighs words by their importance in the corpus."
]

# 1. Bag‑of‑Words
bow_vectorizer = CountVectorizer()
X_bow = bow_vectorizer.fit_transform(documents)
print("BoW feature names:", bow_vectorizer.get_feature_names_out())
print("BoW vector (#docs × #terms):\n", X_bow.toarray())

# 2. TF‑IDF
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(documents)
print("\nTF-IDF feature names:", tfidf_vectorizer.get_feature_names_out())
print("TF-IDF matrix:\n", X_tfidf.toarray())

# 3. n‑grams (using bi‑grams)
bigram_vectorizer = CountVectorizer(ngram_range=(2,2))
X_bigram = bigram_vectorizer.fit_transform(documents)
print("\nBi-gram feature names:", bigram_vectorizer.get_feature_names_out())
print("Bi-gram BoW matrix:\n", X_bigram.toarray())


BoW feature names: ['by' 'converts' 'corpus' 'extraction' 'fascinating' 'feature' 'idf'
 'importance' 'in' 'is' 'learning' 'machine' 'text' 'tf' 'the' 'their'
 'to' 'vectors' 'weighs' 'words']
BoW vector (#docs × #terms):
 [[0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 0 0 0 0 0 2 0 0 0 1 1 0 0]
 [1 0 1 0 0 0 1 1 1 0 0 0 0 1 1 1 0 0 1 1]]

TF-IDF feature names: ['by' 'converts' 'corpus' 'extraction' 'fascinating' 'feature' 'idf'
 'importance' 'in' 'is' 'learning' 'machine' 'text' 'tf' 'the' 'their'
 'to' 'vectors' 'weighs' 'words']
TF-IDF matrix:
 [[0.         0.         0.         0.         0.5        0.
  0.         0.         0.         0.5        0.5        0.5
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.33333333 0.         0.33333333 0.         0.33333333
  0.         0.         0.         0.         0.         0.
  0.66666667 0.         0.         0.         0.33333333 0.33333333
  0.         0.        ]
 [0.316